### ISSUE TITLE
Sanitization addition?

### ISSUE THREAD

**Issue by rietta** [holli/auto_strip_attributes#18]
Would you be open to a pull request to add sanitization - aka running Loofah sanitization to remove XSS code from user submitted input that may be then added to the database?

It's normally thought of as a view concern in Rails, but there are other apps that interact with databases so a defense in depth approach of not letting known-unsafe markup to be persisted is wise in many use cases.

Frank

**Comment by holli** [comment]
I don't think those should be added to the basic gem as those add extra dependencies and often require custom options in different apps. E.g. do you want to remove everything suspicious or maybe permit some specific tags.

I have my self used strip_tags option, as in the example: https://github.com/holli/auto_strip_attributes#custom-filters 

Although if people have good little snippets they could be added to the wiki page.
