### ISSUE TITLE
Problem with numericality (validation helper)

### ISSUE THREAD

**Issue by chayawit** [holli/auto_strip_attributes#21]
I'm new to Ruby and RoR, so I'm sorry if this issue is not related to the gem.

In my model I have these lines.

```
auto_strip_attributes :price
validates :price, numericality: {greater_than_or_equal_to: 0}
```

I tested with negative number and get 'Price must be greater than or equal to 0', which was expected.

The problem is when I test with alphabets, if I remove the `auto_strip_attributes` line I will get 'Price is not a number'. But with the `auto_strip_attributes` line, the `price` field passes validation with the value of `0`.

**Comment by holli** [comment]
Hmm. Yep that's not really how one would expected the gem to work. But in a sense there are not really any reasons to use auto_strip_attributes on integers etc. If I recall correctly in with number inputs Rails uses to_i or to_f methods which will do the necessary work `"    -3.14159   ".to_f    => -3.14159`. So the gem is needed only with strings.

**Comment by chayawit** [comment]
Yes. I realized later that Rails strips down the spaces in the front and back. So I don't need to use auto_strip_attributes anymore for this requirement.

However, I am wondering what if I have to use :delete_whitespaces filter?
It's not that I have an example use case right now but just an idea.
