### ISSUE TITLE
Follow SemVer 2.0

### ISSUE THREAD

**Issue by pboling** [holli/auto_strip_attributes#25]
https://semver.org/

It appears from the changelog that this project may be loosely following semver.  However, it seems that perhaps some releases would have rather been patch levels (the most recent 2), and others major version bumps (dropping support for a Ruby version).

When using tools like [Depfu](https://depfu.com) it is of unestimable value when the library in question follows SemVer.

**Comment by holli** [comment]
I'll try to follow semver. Hmm. The two most recent releases added some functionality that was not previously found. Isn't it then minor version? From semver.org: `MINOR version when you add functionality in a backwards-compatible manner, ...`

I'm not totally sure about dropping an old Ruby version what it should be. If the drop is only about dropping tests for old non supported Ruby and not changing anything about api.

**Comment by holli** [comment]
gemspec maybe could include info about ruby version, mut I'm not sure how that works or does it limit away also jruby etc that is now working. I'd be happy to take a pull request if someone makes it.
