### ISSUE TITLE
Use `ActiveSupport.on_load` to hook into ActiveRecord

### ISSUE THREAD

**Issue by jeffblake** [holli/auto_strip_attributes#26]
See details here: https://github.com/rails/rails/issues/23589

And here: https://github.com/activerecord-hackery/ransack/issues/797

**Comment by holli** [comment]
- so change https://github.com/holli/auto_strip_attributes/blob/master/lib/auto_strip_attributes.rb#L96
- example of how to use: https://github.com/plataformatec/devise/commit/c2c74b0a39238e7d997486814a1c8f75fdaf276f
- (this might also fix https://github.com/holli/auto_strip_attributes/issues/22)
