### ISSUE TITLE
support non-persistent attributes that are set with attr_accessor

### ISSUE THREAD

**Issue by Nowaker** [holli/auto_strip_attributes#9]
I've got an Active Record model with some columns, and one fake field set with `attr_accessor`. I'd like to get this pseudofield stripped as well.

```
attr_accessor :password
auto_strip_attributes :password
```

**Comment by jeffblake** [comment]
This would also be great for those using hstore_accessor gem or store_accessor

**Comment by holli** [comment]
New version of the gem includes options for this one.
